# https://docs.travis-ci.com/user/languages/python/
language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install pyinstaller
script: pyinstaller --clean --windowed --onedir --onefile --add-data Scripts:Scripts ProperTree.command
